routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GaleriController;
use App\Http\Controllers\FotoController;

//landing page
Route::get('/', function () {
    return view('umum.index');
}); 

//login
Route::get('/register', 'AuthController@isidata');
Route::post('/kirim', 'AuthController@send');
Route::get('/home', 'HomeController@index')->name('home');

//CRUD  
Route::resource('/user', 'UserController'); 
Route::resource('/kategori', 'KategoriController'); 
Route::resource('/profile', 'ProfileController'); 
Route::resource('/galeri', 'GaleriController'); 
Route::resource('/foto', 'FotoController'); 
Auth::routes();




//Route::get('/profile/create', 'ProfileController@create');
//Route::post('/profile/create', 'ProfileController@create');

app/galeri.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class galeri extends Model
{
    protected $table ='galeri';
    protected $fillable = [ 
        'judul', 'gambar', 'users_id'
    ];
   // public function kategori()
   // {
   //   return $this->belongsTo('App\kategori','foto,', 'galeri_id', 'kategori_id');    
   // }
   public $timestamps = false;

   

}

app/Http/Controllers/GaleriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\galeri;
use App\users;
use File;

class GaleriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct() {
        $this->middleware('auth');
      }

    public function index()
    {
    $galeri = Galeri::all();
       return view('galeri.index', compact('galeri'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = users::all();
        return view('galeri.create', compact('users')); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'judul' => 'required',  
            'gambar' => 'required|mimes:png,jpg,jpeg',
            'users_id' => 'required',
        ]);
 


    $fileName = time().'.'.$request->gambar->extension(); 
    $users = new Galeri; 
    $users->judul = $request->judul; 
    $users->gambar = $fileName;
    $users->users_id = $request->users_id; 
    $users->save(); 
    $request->gambar->move(public_path('gm'), $fileName); 
    return redirect('galeri/create'); 
} 

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $galeri = Galeri::findorfail($id);
        return view('galeri.show', compact('galeri'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = users::all(); 
        $galeri = Galeri::findorfail($id);
        return view('galeri.edit', compact('galeri','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'judul' => 'required',  
            'gambar' => 'mimes:png,jpg,jpeg',
            'users_id' => 'required',
        ]);

        $galeri = Galeri::findorfail($id);
        if ($request->has('gambar')) {

            $path = "gm/";
            File::delete($path . $galeri->gambar);
            $fileName = time().'.'.$request->gambar->extension(); 

            $request->gambar->move(public_path('gm'), $fileName); 

            $galeri_data = [
                'judul' => $request->judul,
                'gambar' => $fileName,
                'users_id' => $request->users_id,
            ];
        }else {
            $galeri_data = [
                'judul' => $request->judul, 
                'users_id' => $request->users_id,
            ]; 
        }
        $galeri->update($galeri_data);
        return redirect('/galeri');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $galeri = Galeri::findorfail($id);

        $path = "gm/";
        File::delete($path . $galeri->gambar);
        $galeri->delete();

        return redirect('/galeri');
    }
}

resources/views/galeri/create.blade.php
@extends('admin.master')

@section('content')
  <div class="row">
    <div class="col-lg-12"> 
      <div class="card">
        <div class="card-body"> 
          <h5 class="card-title">Tambah Data Galeri</h5>
  
          <!-- General Form Elements --> 
          <form method="POST" action="/galeri" enctype="multipart/form-data">
            @csrf 
            <div class="row mb-3">
              <label  class="col-sm-2 col-form-label">Judul</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name="judul" placeholder="Masukkan judul">
                @error('nama')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
                 @enderror
              </div>
            </div>
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Upload Gambar</label>
                <div class="col-sm-10">
                  <input class="form-control" type="file" name="gambar">
                </div>
              </div> 
              <div class="row mb-3">
                <label class="col-sm-2 col-form-label">User ID</label>
                <div class="col-sm-10">
                  <select class="form-select" name="users_id" id="#">
                      <option>---Pilih ID User Anda---</option>
                    @foreach ($users as $item)
                    <option value="{{$item->id}}">{{$item->name}}</option>
                        
                    @endforeach
                  </select>
                </div>
              </div>  
              <!--<div class="row mb-3">
                <label class="col-sm-2 col-form-label">User ID</label>
                <div class="col-sm-10">
                  <select class="form-select" name="users_id" id="#">
                      <option>---Pilih ID User Anda---</option>
                    @foreach ($users as $item)
                    <option value="{{$item->id}}">{{$item->name}}</option>
                        
                    @endforeach
                  </select>
                </div>
              </div> -->
              <div class="row mb-3"> 
                <div class="col-sm-10">
                  <button type="submit" class="btn btn-primary">Create</button>   
                 <a href="{{ route('galeri.index')}}" class="btn btn-danger">Cancel</a>
                </div>
              </div>  
          </form>  
        </div>
      </div> 
    </div> 
  </div>
@endsection

resources/views/galeri/edit.blade.php
@extends('admin.master')

@section('content')
  <div class="row">
    <div class="col-lg-12"> 
      <div class="card">
        <div class="card-body"> 
          <h5 class="card-title">Edit Data Galeri</h5>
  
          <!-- General Form Elements --> 
          <form method="POST" action="/galeri/{{$galeri->id}}" enctype="multipart/form-data">
            @csrf 
            @method('put')
            <div class="row mb-3">
              <label  class="col-sm-2 col-form-label">Judul</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name="judul" value="{{$galeri->judul}}">
                @error('nama')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
                 @enderror
              </div>
            </div>
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Upload Gambar</label>
                <div class="col-sm-10">
                  <input class="form-control" type="file" name="gambar">
                </div>
              </div> 
              <div class="row mb-3">
                <label class="col-sm-2 col-form-label">User ID</label>
                <div class="col-sm-10">
                  <select class="form-select" name="users_id" id="#">
                      <option>---Pilih ID User Anda---</option>
                    @foreach ($users as $item)
                    @if ($item->id === $galeri->users_id)
                    <option value="{{$item->id}}" selected>{{$item->name}}</option>                        
                    @else
                    <option value="{{$item->id}}">{{$item->name}}</option>
                        
                    @endif
                    @endforeach
                  </select>
                </div>
              </div>  
              <div class="row mb-3"> 
                <div class="col-sm-10">
                  <button type="submit" class="btn btn-primary">Edit</button>   
                 <a href="{{ route('galeri.index')}}" class="btn btn-danger">Cancel</a>
                </div>
              </div>  
          </form>  
        </div>
      </div> 
    </div> 
  </div>
@endsection

resources/views/galeri/index.blade.php
@extends('admin.master')

@section('content')
<div class="col-lg-12">  
      <h5 class="card-title">Data Galeri</h5>
        <a href="{{ route('galeri.create') }}" class="btn btn-primary rounded-pill">Tambah Data</a> <br><br>
          <div class="row"> 
              @forelse ($galeri as $item) 
                <div class="col-lg-6">
                  <!-- Card with an image on top -->
                  <div class="card">
                    <img src="{{asset('gm/'.$item->gambar)}}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{$item->judul}}</h5>
                       
                        <form action="{{ route('galeri.destroy', $item->id)}}" method="POST">
                          @csrf
                          <a href="{{route('galeri.show', $item->id)}}" class="btn btn-info rounded-pill">Detail</a>
                          <a href="{{route('galeri.edit', $item->id)}}" class="btn btn-warning rounded-pill">Edit</a> 
                          @method('delete')
                          <input type="submit" class="btn btn-danger rounded-pill" value="Delete">
                        </form>
                      
                      </div>
                  </div><!-- End Card with an image on top -->
                </div>
                @empty
                <p> Kosong</p>
              @endforelse 
  </div>
</div>
@endsection

resources/views/galeri/show.blade.php
@extends('admin.master')

@section('content')
<h5 class="card-title">Detail Galeri</h5>
<div class="card mb-3">
    <div class="row g-0"> 
        <img src="{{asset('gambar/'.$galeri->gambar)}}" width="500px"  class="img-fluid rounded-start" alt="...">
       
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{$galeri->judul}}</h5>
        </div>
      </div>
      <div class="row mb-3"> 
        <div class="col-sm-10">
          <a href="{{ route('galeri.index')}}" class="btn btn-success">Back</a> 
        </div>
      </div> 
    </div>
  </div>
  @endsection